import { afterEach, describe, expect, it, vi } from "vitest";
import { createCommentCadence, startVisiblePolling } from "../src/components/comments/comment-polling";

afterEach(() => vi.useRealTimers());
describe("comment polling", () => {
  it("honors the retry floor on foreground and contains rejected requests", async () => {
    vi.useFakeTimers();
    const visibility = Object.assign(new EventTarget(), { hidden: false });
    const focus = new EventTarget();
    let retryAt = 0;
    const run = vi.fn(async () => { retryAt = Date.now() + 60000; throw new Error("offline"); });
    const stop = startVisiblePolling(run, wake => Math.max(wake ? 0 : 10000, retryAt - Date.now()), visibility, focus);
    await vi.advanceTimersByTimeAsync(0);
    await vi.advanceTimersByTimeAsync(5000);
    visibility.hidden = true;
    visibility.dispatchEvent(new Event("visibilitychange"));
    visibility.hidden = false;
    visibility.dispatchEvent(new Event("visibilitychange"));
    focus.dispatchEvent(new Event("focus"));
    await vi.advanceTimersByTimeAsync(54999);
    expect(run).toHaveBeenCalledTimes(1);
    await vi.advanceTimersByTimeAsync(1);
    expect(run).toHaveBeenCalledTimes(2);
    stop();
  });

  it("backs off unchanged snapshots and resets after a change or interaction", () => {
    const cadence = createCommentCadence();
    expect(cadence.accept("a")).toBe(10000);
    expect(cadence.accept("a")).toBe(20000);
    expect(cadence.accept("a")).toBe(30000);
    expect(cadence.accept("a")).toBe(30000);
    expect(cadence.accept("b")).toBe(10000);
    cadence.accept("b");
    expect(cadence.accept("b", true)).toBe(10000);
  });
  it("stops hidden timers, coalesces foreground events and cleans up", async () => {
    vi.useFakeTimers();
    const visibility = Object.assign(new EventTarget(), { hidden: false });
    const focus = new EventTarget();
    const run = vi.fn(async () => {});
    const stop = startVisiblePolling(run, wake => wake ? 0 : 10000, visibility, focus);
    await vi.advanceTimersByTimeAsync(0);
    expect(run).toHaveBeenCalledTimes(1);
    visibility.hidden = true;
    visibility.dispatchEvent(new Event("visibilitychange"));
    expect(vi.getTimerCount()).toBe(0);
    await vi.advanceTimersByTimeAsync(60000);
    expect(run).toHaveBeenCalledTimes(1);
    visibility.hidden = false;
    visibility.dispatchEvent(new Event("visibilitychange"));
    focus.dispatchEvent(new Event("focus"));
    await vi.advanceTimersByTimeAsync(0);
    expect(run).toHaveBeenCalledTimes(2);
    await vi.advanceTimersByTimeAsync(100);
    focus.dispatchEvent(new Event("focus"));
    await vi.advanceTimersByTimeAsync(0);
    expect(run).toHaveBeenCalledTimes(2);
    stop();
    focus.dispatchEvent(new Event("focus"));
    await vi.advanceTimersByTimeAsync(60000);
    expect(run).toHaveBeenCalledTimes(2);
  });
  it("does not overlap slow requests or queue duplicate focus refreshes", async () => {
    vi.useFakeTimers();
    const visibility = Object.assign(new EventTarget(), { hidden: false });
    const focus = new EventTarget();
    let finish!: () => void;
    const run = vi.fn(() => new Promise<void>(resolve => { finish = resolve; }));
    const stop = startVisiblePolling(run, () => 30000, visibility, focus);
    await vi.advanceTimersByTimeAsync(0);
    focus.dispatchEvent(new Event("focus"));
    focus.dispatchEvent(new Event("focus"));
    await vi.advanceTimersByTimeAsync(60000);
    expect(run).toHaveBeenCalledTimes(1);
    finish();
    await vi.advanceTimersByTimeAsync(29999);
    expect(run).toHaveBeenCalledTimes(1);
    await vi.advanceTimersByTimeAsync(1);
    expect(run).toHaveBeenCalledTimes(2);
    stop();
    finish();
    await vi.advanceTimersByTimeAsync(0);
    expect(vi.getTimerCount()).toBe(0);
  });
  it("does not fetch on hidden mount and resumes when visible", async () => {
    vi.useFakeTimers();
    const visibility = Object.assign(new EventTarget(), { hidden: true });
    const run = vi.fn(async () => {});
    const stop = startVisiblePolling(run, wake => wake ? 0 : 10000, visibility, new EventTarget());
    await vi.advanceTimersByTimeAsync(60000);
    expect(run).not.toHaveBeenCalled();
    visibility.hidden = false;
    visibility.dispatchEvent(new Event("visibilitychange"));
    await vi.advanceTimersByTimeAsync(0);
    expect(run).toHaveBeenCalledWith(true);
    stop();
  });
});
