"use client";
import { siteFetch as fetch } from "@/lib/share-context";

// Pure visual editing: double-click text in the live preview to rewrite it directly, with no source code and no
// file list in sight. The edit frame comes from /api/sites/:slug/edit-frame — fetched with fetch (the edit
// credential goes in a HEADER and never into the URL, otherwise a token equivalent to the owner's would land inside
// a document that runs third-party JS), then handed as srcDoc to a sandboxed iframe without allow-same-origin.
//
// [The channel to the iframe: a MessagePort, not window messages]
// The artifact's own JS and the injected bootstrap share the same document and the same realm, and neither
// `e.source === iframe.contentWindow` nor `data.nonce` **can tell them apart**: the nonce is written right into
// the bootstrap script's textContent, so the artifact script has it the moment it reads it; and racing to answer
// first is deterministically possible — save() below attaches `pending` synchronously before postMessage, so an
// artifact script spamming forged patches via setInterval(...,0) is guaranteed to be resolved first, and the real
// reply arriving later is simply dropped. A forged patch would even pass validation (el/i read from the DOM,
// `before` taken from the page's original text); the result is that a user editing their own fork gets its body
// silently rewritten, and the audit log records it as the user's own method=visual edit.
// Hence: a MessageChannel is created here and port2 is transferred to the bootstrap along with the ping; from then
// on ready/dirty/patch/saved travel exclusively over this private channel, and equivalent messages on window are
// never trusted again (no listener is even attached).
//
// Saving does not serialize the DOM back; it asks the iframe for a "text patch" and applies the replacements to
// the **original source string** (lib/text-writeback), then POSTs it as an ordinary content edit (method=visual
// lets the audit log record how the change was made; the save endpoint re-authorizes). Not a single unmappable
// patch is silently dropped: the user is told on the spot how many passages were not written back, and the iframe
// is **not** told to clear them along with the rest (only the ones that actually landed are cleared, by key).
import { useCallback, useEffect, useRef, useState } from "react";
import { AlertTriangle, Code2, Eye, Info, Loader2, MousePointerClick, RotateCw } from "lucide-react";
import { applyTextPatches, type TextPatch } from "@/lib/text-writeback";
import { DEFAULT_LOCALE, translatorFor, type Translator } from "@/lib/i18n";
import { useT } from "@/components/locale-provider";

/** English fallback for the pure helpers below when no translator is handed in (tests, non-React callers). */
const englishT: Translator = translatorFor(DEFAULT_LOCALE);

type Phase = "loading" | "framing" | "ready" | "error";

type FrameMessage = {
  type?: string;
  nonce?: string;
  count?: number;
  patches?: unknown[];
  reason?: unknown;
  editable?: unknown;
  script?: unknown;
  structure?: unknown;
  copied?: unknown;
  previewing?: unknown;
  playing?: unknown;
};

/** The longest we wait for the bootstrap to report in after the edit frame is mounted. */
export const READY_DEADLINE_MS = 8000;
/** Resend the handshake ping while ready has not arrived (the iframe's load may be held up by slow resources). */
const HANDSHAKE_RETRY_MS = 600;

/**
 * The explanation shown when the bootstrap never reports in. There used to be no terminal state here: when the
 * artifact ships its own `<meta http-equiv="Content-Security-Policy">` that blocks inline scripts, or its script
 * rewrites the whole document via document.write and flushes the injected <script>, the UI sat on "Loading"
 * forever, and after 4 seconds even lied with a "the page is rather large" line.
 */
export const FRAME_BLOCKED_MESSAGE =
  "This page blocked the editing script (usually because the artifact ships its own Content-Security-Policy, or its script rewrote the whole document), so visual editing cannot be used. Please use Edit source instead.";

/**
 * The notice for a failed mapping. It used to blame "this text was generated by the page script" every time — very
 * often it was nothing of the sort; the scanner itself has structures it cannot cover, and a definitive claim would
 * mislead the user and whoever debugs it alike. Name the cause when it can be distinguished; otherwise state only the fact.
 *
 * The semantics of this set of reasons were revised once along with the "first occurrence wins" rule (see the file
 * header of lib/editor-bootstrap):
 *   · `copy`      The one you double-clicked is a copy made by a script; the one in the main content **can be
 *                 edited**. Formerly called `duplicate`, meaning "this marker is not unique on the page" — that
 *                 criterion condemned the whole page, which is precisely the bug being fixed here.
 *   · `replaced`  The one in the main content has already been swapped out of the page by a script; only copies
 *                 remain on the page: nobody can edit it.
 *   · `structure` The element is still there, but its runtime text structure does not match the source.
 *   · other/none  The cause cannot be stated; only the fact is.
 */
export function unmappableNotice(reason?: unknown, t: Translator = englishT): string {
  // `duplicate` is the name from before the criterion changed. It is kept so that a cross-version edit frame (the
  // parent page is already new, while the iframe still runs the script injected by the previous deployment) does
  // not fall through to the vaguest fallback line.
  if (reason === "copy" || reason === "duplicate") {
    return t("This text is a copy made by the page script (typical of thumbnails and preview panes); changing it would not touch the source. Edit the one in the main content instead — that one can be double-clicked and edited directly.");
  }
  if (reason === "replaced") {
    return t("The original of this text has been replaced on the page by its script; only a copy remains, so the change cannot be written back safely. Please use Edit source to change it.");
  }
  if (reason === "structure") {
    return t("The runtime structure of the element holding this text does not match the source (the page script inserted nodes), so the change cannot be written back safely. Please use Edit source to change it.");
  }
  return t("This text cannot currently be mapped back to the source. You can change it with Edit source.");
}

/** What the bootstrap reports: "how much of this page can be edited, and why the rest cannot". */
export interface FrameStats {
  /** Number of text passages that can be rewritten by double-clicking. */
  editable: number;
  /** Number of text passages generated at runtime by the page script (absent from the source altogether; only source editing can change them). */
  script: number;
  /** Number of text passages whose runtime structure does not match the source. */
  structure: number;
  /** Number of text passages whose original was swapped out by a script, leaving only copies on the page. */
  copied: number;
}

function counted(value: unknown): number {
  return typeof value === "number" && Number.isFinite(value) && value >= 0 ? Math.floor(value) : 0;
}

/** The stats arrive via postMessage from the iframe; their shape cannot be treated as trusted input. */
export function readFrameStats(raw: { editable?: unknown; script?: unknown; structure?: unknown; copied?: unknown }): FrameStats {
  return {
    editable: counted(raw.editable),
    script: counted(raw.script),
    structure: counted(raw.structure),
    copied: counted(raw.copied),
  };
}

export interface StatsCopy {
  /** The persistent explanation line on the toolbar. */
  line: string;
  /** Not a single passage can be edited: do not let the user click around blindly; push "Edit source" forward right away. */
  blocked: boolean;
}

/**
 * On entering the editor, spell out "how much of this page can be edited, how much cannot, and why", instead of
 * waiting for the user to double-click and then popping a refusal. The user's own words were: "I'm already in
 * here and still can't edit; popping that notice is weird."
 */
export function statsCopy(stats: FrameStats, t: Translator = englishT): StatsCopy {
  const reasons: string[] = [];
  if (stats.script > 0) reasons.push(t("{count} passages generated by the page script", { count: stats.script }));
  if (stats.structure > 0) reasons.push(t("{count} passages whose structure does not match the source", { count: stats.structure }));
  if (stats.copied > 0) reasons.push(t("{count} passages left only as copies made by a script", { count: stats.copied }));
  if (stats.editable === 0) {
    return {
      blocked: true,
      line: reasons.length
        ? t("This page has no text that can be edited by double-clicking ({reasons}); visual editing cannot reach any passage in the source. Please use Edit source.", { reasons: reasons.join(t(", ")) })
        : t("No editable text was found on this page. Please use Edit source."),
    };
  }
  return {
    blocked: false,
    line: reasons.length
      ? t("{count} passages on this page can be edited; another {reasons} need Edit source.", { count: stats.editable, reasons: reasons.join(t(", ")) })
      : t("All {count} passages on this page can be edited directly.", { count: stats.editable }),
  };
}

/**
 * The URL of the edit frame. With a baseVersionId, the server serves that version's entry HTML, markers are computed
 * against **that version's source**, and the `x-ah-editor-version` response header returns it too; without one, the
 * current version is used as before.
 */
export function editFrameUrl(slug: string, baseVersionId?: string | null): string {
  const base = `/api/sites/${slug}/edit-frame`;
  return baseVersionId ? `${base}?version=${encodeURIComponent(baseVersionId)}` : base;
}

/**
 * Which version `x-ah-editor-version` should equal for this fetch of the edit frame.
 *
 * "Drift" means **someone else** changed this site without you knowing (the source in hand is then stale, offsets
 * would be misaligned, and the only option is to make the user refresh). When the user deliberately picked a
 * historical version as the base, that version is exactly what they want, and it is exactly what the server serves —
 * that is a different matter from drift. So with a baseVersionId the expected value is that id, not the baseline
 * that advances with every save; otherwise saving once on a historical version (baseline moves forward to the new
 * version) and then reloading the edit frame would be misreported by your own save as "This site was updated elsewhere".
 */
export function expectedFrameVersion(baseVersionId: string | undefined, baseline: string): string {
  return baseVersionId || baseline;
}

/**
 * The explanation when the source in hand and the edit frame are not the same version. Marker indices are computed
 * against the server's copy of the source, so a version mismatch means the offsets would be misaligned, and writing
 * anyway would corrupt the file — the only option is to make the user refresh.
 */
export const VERSION_DRIFT_MESSAGE = "This site was updated elsewhere. Refresh the page before editing";

export interface VersionGate {
  /** Whether editing can continue with the source in hand. false = real drift; the user must refresh. */
  ok: boolean;
  /** If the served version should be adopted as the new baseline, this is it; null = baseline unchanged. */
  adopt: string | null;
}

/**
 * How to handle `x-ah-editor-version` when the edit frame is reloaded.
 *
 * `selfSaved` is the crucial cell: when **we ourselves just saved** and the save response did not carry the new
 * version id back (see reloadOutdatesBaseline), the server's version is necessarily newer than the baseline in hand
 * — the "mismatch" here was caused by the user, not by someone else changing the site. This used to report "This
 * site was updated elsewhere. Refresh the page before editing" unconditionally: the user cleared a passage to empty
 * (which triggers a reload), the save plainly succeeded, and the UI immediately threw a "someone else changed it" at
 * them, leaving refresh-and-redo as the only way out. In that case `served` is exactly the version we just wrote,
 * so it is adopted as the new baseline outright.
 */
export function checkServedVersion(served: string | null, baseline: string, selfSaved: boolean): VersionGate {
  if (!served) return { ok: true, adopt: null }; // the server reported no version, so there is nothing to compare
  if (selfSaved) return { ok: true, adopt: served };
  if (served !== baseline) return { ok: false, adopt: null };
  return { ok: true, adopt: null };
}

/**
 * Whether this reload will make the baseline version id in hand stale.
 *
 * It counts only when all three hold at once: "a POST really happened + the response had no versionId + the edit
 * frame is about to be reloaded". Today `/api/sites/:slug/edit` **always** returns versionId (the route reads
 * result.version.id directly), so this is a defensive branch: a response body mangled by a middle layer, or an
 * endpoint that one day omits the field, both land here. The cost is a single ref; what it blocks is the "user
 * saves and is told the site was updated elsewhere" false alarm that nobody could diagnose on their own.
 * The path without a reload needs no handling: the version check only happens when the edit frame is re-fetched,
 * and after a save the only thing that re-fetches immediately is reload.
 */
export function reloadOutdatesBaseline(posted: boolean, savedVersion: string | null, willReload: boolean): boolean {
  return posted && !savedVersion && willReload;
}

export interface WritebackPlan {
  /** Patches handed to the iframe to clear by key — only the ones that **were actually written back to the source**. */
  savedKeys: string[];
  /** The whole edit frame needs reloading (markers must be recomputed against the new source). */
  reload: boolean;
  /** After clearing patches / reloading, are there still unsaved changes on the page? */
  dirtyAfter: boolean;
  notice: string | null;
}

/**
 * How to wrap up after a save. Pulled out on its own because one wrong step here means **silently losing
 * changes**: previously, as long as applied.length>0, ah-editor:saved was sent to the iframe unconditionally, and
 * on receiving it the bootstrap did `patches={}`, clearing **all** patches (including the ones not written back).
 * The user saw "N passages could not be written back", yet the page still showed the new text, the unsaved badge
 * disappeared, and clicking Save again said "No changes yet" — those changes were lost for good with no way to retry.
 */
export function planWriteback(applied: readonly TextPatch[], skipped: readonly TextPatch[], t: Translator = englishT): WritebackPlan {
  // Clearing a passage to empty makes it vanish from the source entirely, and the indices of the following text
  // nodes in the same element shift accordingly — the markers in hand no longer match, so the whole edit frame must
  // be reloaded (the passages that were not written back revert to the original source text as a result, which
  // has to be said plainly).
  const remark = applied.some((p) => p.text.trim() === "");
  const missed = skipped.length;
  if (remark) {
    return {
      savedKeys: [],
      reload: true,
      dirtyAfter: false,
      notice: missed
        ? t("Saved. Not written back: {missed}. The editor was reloaded with the new version, so those passages have reverted to the original source text. Please use Edit source to change them.", { missed })
        : null,
    };
  }
  return {
    savedKeys: applied.map((p) => `${p.el}:${p.i}`),
    reload: false,
    dirtyAfter: missed > 0,
    notice: missed
      ? t("Changes saved: {count}. Not written back: {missed} (the text in the source no longer matches); they remain marked as unsaved. Please use Edit source to change them.", { count: applied.length, missed })
      : null,
  };
}

/** What the page's toolbar needs from the visual editor — see the onState prop. */
export interface VisualEditorState {
  previewing: boolean;
  dirty: boolean;
  busy: boolean;
  /** The frame has completed the handshake; before that neither switch nor save can do anything. */
  ready: boolean;
  togglePreview: (preview: boolean) => void;
  save: () => void;
}

export default function VisualEditor({
  slug,
  kind,
  entry,
  versionId,
  baseVersionId,
  source,
  editToken,
  onSaved,
  onDirtyChange,
  onFallback,
  onState,
}: {
  slug: string;
  kind: "single" | "folder";
  /** Relative path of the entry HTML; folder sites write back this one file by path when saving. */
  entry: string;
  /** The version the parent page's copy of the source belongs to; if it does not match the version reported by edit-frame, saving is not allowed. */
  versionId: string;
  /**
   * A historical version the user deliberately picked as the base. When given, the edit frame is fetched for that
   * version (and markers are computed against that version's source); when absent, the current version is used.
   * Changing the value restarts the whole edit frame on the new version.
   */
  baseVersionId?: string;
  /** The **original source** of the entry HTML — text write-back is done on it and nothing else. */
  source: string;
  editToken: string | null;
  /** Save succeeded: hand the new source and version id back to the parent page, so the source editor / version id can catch up. */
  onSaved: (content: string, newVersionId: string | null) => void;
  /** Whether there are unsaved changes (the parent page uses this to guard navigation away). */
  onDirtyChange: (dirty: boolean) => void;
  /** This site cannot be edited visually (or the user chose not to) → the parent page switches back to source editing. */
  onFallback: (reason: string) => void;
  /**
   * The state the page's toolbar renders: Edit / Preview and Save live in the header (the design's one bar),
   * but the mode, the dirty flag and the save itself belong to the frame's channel, which only this component
   * holds. Reported whenever any of it changes; the parent renders the controls from the latest report.
   */
  onState?: (state: VisualEditorState) => void;
}) {
  const t = useT();
  const [phase, setPhase] = useState<Phase>("loading");
  const [srcDoc, setSrcDoc] = useState<string | null>(null);
  const [dirty, setDirty] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [slow, setSlow] = useState(false);
  const [frameKey, setFrameKey] = useState(0);
  const [stats, setStats] = useState<FrameStats | null>(null);
  // Preview mode: hand the page back to the artifact (its own keys, clicks and controls all work as usual), while edited-but-unsaved text stays in place.
  const [previewing, setPreviewing] = useState(false);

  const iframeRef = useRef<HTMLIFrameElement | null>(null);
  const nonceRef = useRef<string | null>(null);
  const versionRef = useRef(baseVersionId ?? versionId);
  /** Skip the version check on the next edit-frame fetch (we just saved ourselves, so the baseline is bound to be behind). See reloadOutdatesBaseline. */
  const skipVersionCheckRef = useRef(false);
  const portRef = useRef<MessagePort | null>(null);
  const pending = useRef<((patches: unknown[]) => void) | null>(null);

  const dropPort = useCallback(() => {
    const port = portRef.current;
    portRef.current = null;
    pending.current = null;
    if (port) { port.onmessage = null; try { port.close(); } catch { /* already closed */ } }
  }, []);

  // Reload the edit frame. Returning to the loading state is done here (in the event handler), and the effect only
  // fetches the data — a synchronous setState inside an effect body would cause cascading renders.
  const reload = useCallback(() => {
    dropPort();
    setPhase("loading");
    setSrcDoc(null);
    setSlow(false);
    setError(null);
    setDirty(false);
    setStats(null);
    setFrameKey((k) => k + 1);
  }, [dropPort]);

  // The user picked a different historical version as the base: markers must be recomputed against that version's
  // source, so the whole edit frame starts over. This uses the "adjust state in place when props change" pattern
  // (comparing against the previous value during render), because it has to take effect before the fetch effect
  // below runs — inside an effect it would first render one frame of "old version, editable" with the stale phase.
  // Only baseVersionId is watched: versionId advances after every save, and using it as the trigger would mean a
  // reload per save.
  const [pinned, setPinned] = useState(baseVersionId);
  if (pinned !== baseVersionId) {
    setPinned(baseVersionId);
    setPhase("loading");
    setSrcDoc(null);
    setSlow(false);
    setError(null);
    setDirty(false);
    setStats(null);
    setFrameKey((k) => k + 1);
  }

  // Fetch the edit frame. The credential goes in a header; a 409 means this site genuinely is not suited to visual editing, so hand back to the parent page to degrade to source.
  useEffect(() => {
    let cancelled = false;
    // Fetching the source can genuinely be slow; if it is not done after a few seconds, explain that it is still working and offer a way out.
    const slowTimer = window.setTimeout(() => { if (!cancelled) setSlow(true); }, 4000);
    (async () => {
      try {
        const res = await fetch(editFrameUrl(slug, baseVersionId), {
          headers: editToken ? { "x-edit-token": editToken } : {},
        });
        if (cancelled) return;
        if (res.status === 409) {
          const body = await res.json().catch(() => ({}));
          onFallback(typeof body?.error === "string" ? body.error : t("This site can only be edited with Edit source."));
          return;
        }
        if (!res.ok) throw new Error(t("Loading failed ({status})", { status: res.status }));
        nonceRef.current = res.headers.get("x-ah-editor-nonce");
        const served = res.headers.get("x-ah-editor-version");
        // Marker indices are computed against the server's copy of the source. A version mismatch means the source
        // in hand is stale and the offsets would be misaligned — writing anyway would corrupt the file, so the user
        // must refresh. But a mismatch caused by "we just saved ourselves" is not drift: that version is exactly what
        // was just written, so it is adopted as the new baseline (one-shot; cleared once used).
        const selfSaved = skipVersionCheckRef.current;
        skipVersionCheckRef.current = false;
        const gate = checkServedVersion(served, expectedFrameVersion(baseVersionId, versionRef.current), selfSaved);
        if (!gate.ok) throw new Error(t(VERSION_DRIFT_MESSAGE));
        // While pinned to a historical version, served is necessarily that version — it does not say "which version
        // this site is on now", so it must not become the baseline. Otherwise, after the user unpins, the baseline
        // would still sit on that historical version and be misreported as drift.
        if (gate.adopt && !baseVersionId) versionRef.current = gate.adopt;
        const html = await res.text();
        if (cancelled) return;
        setSrcDoc(html);
        setPhase("framing");
      } catch (e) {
        if (!cancelled) { setError(e instanceof Error ? e.message : t("Loading failed")); setPhase("error"); }
      }
    })();
    return () => { cancelled = true; window.clearTimeout(slowTimer); };
  }, [slug, editToken, frameKey, baseVersionId, onFallback, t]);

  // Only handle messages arriving over the **private port**. The nonce is still checked (it pairs this session), but security rests on the port.
  const onFrameMessage = useCallback((raw: unknown) => {
    const data = raw as FrameMessage | null;
    if (!data || data.nonce !== nonceRef.current) return;
    if (data.type === "ah-editor:ready") { setPhase("ready"); setError(null); }
    else if (data.type === "ah-editor:dirty") setDirty((data.count ?? 0) > 0);
    else if (data.type === "ah-editor:stats") setStats(readFrameStats(data));
    else if (data.type === "ah-editor:unmappable") setNotice(unmappableNotice(data.reason, t));
    // The frame's acknowledgement is authoritative, not the moment of the click — the button state changes only once the switch has actually taken effect inside the iframe.
    else if (data.type === "ah-editor:mode") setPreviewing(Boolean(data.previewing ?? data.playing));
    else if (data.type === "ah-editor:patch" && pending.current) {
      const resolve = pending.current;
      pending.current = null;
      resolve(Array.isArray(data.patches) ? data.patches : []);
    }
  }, [t]);

  // Handshake: create a fresh channel and transfer port2 into the iframe along with the ping. The artifact script
  // cannot get hold of the port (the bootstrap calls stopImmediatePropagation), so anything said on this channel
  // afterwards can only come from the bootstrap.
  const handshake = useCallback(() => {
    const win = iframeRef.current?.contentWindow;
    const nonce = nonceRef.current;
    if (!win || !nonce) return;
    dropPort();
    const channel = new MessageChannel();
    portRef.current = channel.port1;
    channel.port1.onmessage = (e: MessageEvent) => onFrameMessage(e.data);
    channel.port1.start();
    win.postMessage({ type: "ah-editor:ping", nonce }, "*", [channel.port2]);
  }, [dropPort, onFrameMessage]);

  // The framing phase must have a terminal state. The ping is resent because the iframe's load may be held up by
  // slow resources; if no ready has been heard by 8 seconds, switch to the error state and give the real cause,
  // rather than spinning on or fobbing the user off with "the page is rather large".
  useEffect(() => {
    if (phase !== "framing") return;
    handshake();
    const retry = window.setInterval(handshake, HANDSHAKE_RETRY_MS);
    const deadline = window.setTimeout(() => {
      setError(t(FRAME_BLOCKED_MESSAGE));
      setPhase("error");
    }, READY_DEADLINE_MS);
    return () => { window.clearInterval(retry); window.clearTimeout(deadline); };
  }, [phase, handshake, t]);

  useEffect(() => dropPort, [dropPort]);

  useEffect(() => { onDirtyChange(dirty); }, [dirty, onDirtyChange]);

  // The notice explains "what just happened"; do not leave it hanging on the toolbar forever.
  useEffect(() => {
    if (!notice) return;
    const t = window.setTimeout(() => setNotice(null), 12000);
    return () => window.clearTimeout(t);
  }, [notice]);

  // The parent page cannot see into the opaque iframe; the dirty flag pushed over the port is the only "something would be lost" signal.
  useEffect(() => {
    if (!dirty) return;
    const h = (e: BeforeUnloadEvent) => { e.preventDefault(); e.returnValue = ""; };
    window.addEventListener("beforeunload", h);
    return () => window.removeEventListener("beforeunload", h);
  }, [dirty]);

  /**
   * Switch between "Edit / Preview" on the **current page**, without navigating away or reloading the edit frame.
   *
   * Why not reload: the pending changes live inside the iframe (the bootstrap's patches + the already-edited text
   * on the page), and a reload would flush them all. So this only sends one message telling the bootstrap to hand
   * over / take back control, and the user can "change a few words → switch to preview to see the real effect →
   * switch back and keep editing" without losing any unsaved content along the way.
   *
   * In preview mode the bootstrap stops intercepting keys and double-click no longer enters edit state; all of the
   * artifact's own interactions come back. Deliberately not called "Play": most artifacts have no notion of
   * playing, and that name would only leave people guessing what the button does.
   */
  const togglePreview = useCallback((next: boolean) => {
    const port = portRef.current, nonce = nonceRef.current;
    if (!port || !nonce) return;
    setNotice(null);
    port.postMessage({ type: "ah-editor:mode", nonce, preview: next, play: next });
    // Switching to preview must hand focus to the iframe; otherwise focus stays on the button just clicked (in the
    // parent document), keystrokes never enter the iframe at all, and none of the artifact's listeners receive them —
    // a user pressing arrow keys right after clicking Preview would conclude "it didn't work".
    // Once the frame element has focus, key events target its document and bubble up to that document, where the
    // artifact gets to handle them.
    if (next) iframeRef.current?.focus();
  }, []);

  const save = useCallback(async () => {
    const port = portRef.current;
    const nonce = nonceRef.current;
    if (!port || !nonce || busy) return;
    setBusy(true);
    setError(null);
    setNotice(null);
    try {
      // Ask the iframe for patches, not the whole page's HTML. If none arrive, time out with an error rather than leaving the UI hung.
      const patches = await new Promise<unknown[]>((resolve, reject) => {
        pending.current = resolve;
        port.postMessage({ type: "ah-editor:save", nonce });
        window.setTimeout(() => {
          if (pending.current) { pending.current = null; reject(new Error(t("The editor is not responding. Please try again"))); }
        }, 5000);
      });
      const result = applyTextPatches(source, patches);
      if (!result.applied.length) {
        throw new Error(patches.length
          ? t("These changes could not be mapped back to the source. Please use Edit source instead")
          : t("No changes yet"));
      }

      let savedVersion: string | null = null;
      let posted = false;
      if (result.html !== source) {
        const body = kind === "single"
          ? { content: result.html, method: "visual" as const }
          : { path: entry, content: result.html, method: "visual" as const };
        const res = await fetch(`/api/sites/${slug}/edit`, {
          method: "POST",
          headers: { "content-type": "application/json", ...(editToken ? { "x-edit-token": editToken } : {}) },
          body: JSON.stringify(body),
        });
        const data = await res.json().catch(() => ({}));
        if (!res.ok) throw new Error(data?.error || t("Save failed ({status})", { status: res.status }));
        posted = true;
        savedVersion = typeof data?.versionId === "string" ? data.versionId : null;
        if (savedVersion) versionRef.current = savedVersion;
      }

      const plan = planWriteback(result.applied, result.skipped, t);
      // Save succeeded but no new version id came back, and the edit frame is about to be reloaded: the server
      // already has the new version, the baseline in hand is bound to be behind, and the check after the reload must
      // be skipped — otherwise the user's own save would be misreported as "This site was updated elsewhere".
      if (reloadOutdatesBaseline(posted, savedVersion, plan.reload)) skipVersionCheckRef.current = true;
      setDirty(plan.dirtyAfter);
      onSaved(result.html, savedVersion);
      if (plan.reload) reload();
      // Clear only the passages that actually landed; the ones not written back stay in the iframe and still count as "unsaved".
      else port.postMessage({ type: "ah-editor:saved", nonce, keys: plan.savedKeys });
      setNotice(plan.notice);
    } catch (e) {
      setError(e instanceof Error ? e.message : t("Save failed"));
    } finally {
      setBusy(false);
    }
  }, [slug, kind, entry, editToken, busy, source, onSaved, reload, t]);

  useEffect(() => {
    onState?.({ previewing, dirty, busy, ready: phase === "ready", togglePreview, save });
  }, [onState, previewing, dirty, busy, phase, togglePreview, save]);

  // When not a single passage can be edited, do not let the user click around blindly: give a clear state right away
  // and push "Edit source" forward as the primary button. Do not block while there are unsaved changes (in theory
  // nothing can be changed when editable=0, but the state is reported by the iframe, so err on the side of caution).
  const summary = stats ? statsCopy(stats, t) : null;
  const blocked = !!summary?.blocked && !dirty;

  return (
    <div className="visual-editor">
      <div className="visual-editor-stage">
        {srcDoc && (
          <iframe
            key={frameKey}
            ref={iframeRef}
            className="visual-editor-frame"
            title={t("Visual editing")}
            srcDoc={srcDoc}
            sandbox="allow-scripts allow-forms allow-modals allow-popups allow-downloads"
            // The handshake is backstopped by the retry loop of the framing phase; onload merely brings it forward a
            // beat. Once connected, do not swap ports again — load may fire very late when held up by slow resources,
            // and swapping the channel then would only interrupt a save in progress.
            onLoad={() => { if (phase !== "ready") handshake(); }}
          />
        )}
        {(phase !== "ready" || blocked) && (
          <div className="ve-loading" role="status" aria-live="polite">
            {phase === "error" ? (
              <>
                <AlertTriangle size={22} aria-hidden="true" />
                <p className="ve-loading-error">{error ?? t("Visual editing failed to load")}</p>
                <div className="ve-loading-actions">
                  <button type="button" className="btn sm ghost" onClick={reload}><RotateCw size={14} /> {t("Retry")}</button>
                  <button type="button" className="btn sm ghost" onClick={() => onFallback(t("Switched to Edit source"))}>
                    <Code2 size={14} /> {t("Use Edit source instead")}
                  </button>
                </div>
              </>
            ) : blocked && summary ? (
              <>
                <AlertTriangle size={22} aria-hidden="true" />
                <p>{summary.line}</p>
                <div className="ve-loading-actions">
                  <button type="button" className="btn sm solid" onClick={() => onFallback(t("This page can only be edited with Edit source"))}>
                    <Code2 size={14} /> {t("Edit source")}
                  </button>
                </div>
              </>
            ) : (
              <>
                <Loader2 size={22} className="spin" aria-hidden="true" />
                <p>{t("Loading visual editing…")}</p>
                {slow && (
                  <p className="ve-loading-slow">
                    {t("Still waiting for this page to be ready. You can also")}{" "}
                    <button type="button" className="ve-link" onClick={() => onFallback(t("Switched to Edit source"))}>{t("use Edit source instead")}</button>.
                  </p>
                )}
              </>
            )}
          </div>
        )}
      </div>
      {/* One line under the canvas, as the design draws it: what to do, how much of the page it applies to, and
          anything that just happened. While editing, the artifact's own keys and clicks are cut off (see pageQuiet
          in editor-bootstrap) — so there is the in-place Preview switch in the header: no navigation, no reload,
          no loss of unsaved changes; look at the result and switch back to keep editing. */}
      <div className="visual-editor-foot">
        <span className="visual-editor-hint">
          {previewing ? (
            <>
              <Eye size={14} aria-hidden="true" /> {t("Previewing: the page has its own interactions back · Switch back to Edit to change text")}
            </>
          ) : (
            <>
              <MousePointerClick size={14} aria-hidden="true" /> {t("Double-click any text to rewrite it · Enter to confirm · Esc to cancel")}
            </>
          )}
        </span>
        {/* Say up front how much of this page can be edited and why the rest cannot — instead of waiting for the user to double-click and then popping a refusal. */}
        {summary && !blocked && (
          <span className="visual-editor-hint" role="status">
            <Info size={13} aria-hidden="true" /> {summary.line}
          </span>
        )}
        {notice && <span className="ve-warn" role="status"><AlertTriangle size={13} aria-hidden="true" /> {notice}</span>}
        {error && <span className="visual-editor-error" role="alert">{error}</span>}
      </div>
    </div>
  );
}
